### ISSUE TITLE
Создать окно для всплывающего уведомления

### ISSUE THREAD

**Issue by selyakovSlava** [selyakovSlava/HappyBirthday#4]
Если сегодня у каких-то пользователей день рождение, то нужно показывать всплывающее уведомление, в котором буду указаны люди, у которых сегодня знаменательный день! 
Показывать Имя и сколько лет ему сегодня исполнилось.

**Comment by vselyakov2304** [comment]
Ок. Сделаю за пару дней! На выходных посижу.

**Comment by selyakovSlava** [comment]
Отлично. Буду ждать!
